### ISSUE TITLE
[css-aliases]  custom selector naming

### ISSUE THREAD

**Issue by bkardell** [tabatkins/specs#25]
Given that we have document.registerElement(), does it make sense to follow suit and call it CSS.registerSelector()?  Seems darn similar in intent and it's nice to be able to apply pieces learned in one part of the platform across the board.

**Comment by tabatkins** [comment]
I think it's more important to hew closer to the CSS name.  As well, the intent of the current API is to use the JS Map API, which I think trumps parallelism with Shadow DOM. ^_^

**Comment by bkardell** [comment]
I can appreciate that you want to close this, but... 

It doesn't really _have_ a CSS name yet, right?  I'm not sure what you mean there -- regardless of what it gets named, I'm not sure why it doesn't still make sense to follow the registerXXX pattern, regardless of what XXX is called. It's conceptually similar nature - at least it would seem to to a dev - don't you think?

Do I misunderstand what you mean entirely?

**Comment by tabatkins** [comment]
I don't want to follow the registerXXX pattern, because that's used by an API with a different shape than what I want.

I want this to be a Map.  You can get/set/delete/etc the values.  registerElement does one thing - sets the key to a value.  It's a different API, and a generally inferior one.

So we have two opposing consistency arguments - consistency with JS's Map, and consistency with DOM's registerElement.  I'm choosing the former, because it gives me more power, and is a better thing to be consistent with anyway imo - lots more code will use Maps in the near future than uses register*-like APIs.
